name: multidevice_dataviz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas>=2.0
  - numpy>=1.24
  - requests>=2.28
  - tzfpy
  - plotly>=5.14
  - ipykernel # For running notebooks in VSCode
  - pip>=23.0
  - pip:
      - setuptools<70.0 # has to be depreciated for ydata-profiling
      - ydata-profiling>=4.6.0


# In the VSCode terminal:
  # conda env create -f environment.yml   
  # conda activate multidevice_dataviz   
  # jupyter viewer  # to launch html viewer