name: multidevice_dataviz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - requests
  - tzfpy
  - folium
  - plotly
  - ipykernel
  - ydata-profiling
  - pip
  - pip:
      - jupyter_viewer   

# In the VSCode terminal:
  # conda env create -f environment.yml   
  # conda activate multidevice_dataviz   
  # jupyter viewer  # to launch html viewer