name: multidevice_dataviz
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip>=23.0
  - pip:
    - -e . # automatically pulls dependencies from pyproject.toml!

## START INITAL DEV SETUP HERE:

# conda env create -f environment.yml
# conda activate multidevice_dataviz
# pip install -e ".[dev,docs]" # can install only dev tools or only docs tools
