# config/sources.yml
# ================================================================================

# DEVICES + access info
# Fitbit google accounts are stored in ./extract/secrets/fitbit/.env.access
# Atmotube hardware ids are stored in .extract/secrets/atmotube/.env.access

fitbit_devices:
  - id: fitbit_kol_01
    type: fitbit
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-06-15 
    end_date: null
    account: !ENV FITBIT_KOL_01_USER
    notes: ""

  - id: fitbit_kol_02
    type: fitbit
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-06-15 
    end_date: null
    account: !ENV FITBIT_KOL_02_USER
    notes: ""

  - id: fitbit_kol_03
    type: fitbit
    site: kolkata
    timezone: Asia/Kolkata
    Start_date: 2026-06-15
    end_date: null
    account: !ENV FITBIT_KOL_03_USER
    notes: ""

  - id: fitbit_kol_04
    type: fitbit
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-06-15
    end_date: null
    account: !ENV FITBIT_KOL_04_USER
    notes: ""

  - id: fitbit_kol_05
    type: fitbit
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-07-03
    end_date: null
    account: !ENV FITBIT_KOL_05_USER
    notes: ""


  - id: fitbit_kol_06
    type: fitbit
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-06-15
    end_date: null
    account: !ENV FITBIT_KOL_06_USER
    notes: ""

atmotube_devices:
  - id: atmotube_kol_01
    type: atmotube
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-06-30  # NOTE: its day AFTER the CSV's last real row, not the API pairing date (for all 2026-07-13, except 07)
    end_date: null
    mac: !ENV ATMOTUBE_KOL_01_MAC

  - id: atmotube_kol_02
    type: atmotube
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-07-03
    end_date: null
    mac: !ENV ATMOTUBE_KOL_02_MAC

  - id: atmotube_kol_03
    type: atmotube
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-06-25
    end_date: null
    mac: !ENV ATMOTUBE_KOL_03_MAC

  - id: atmotube_kol_04
    type: atmotube
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-07-03
    end_date: null
    mac: !ENV ATMOTUBE_KOL_04_MAC

  - id: atmotube_kol_05
    type: atmotube
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-07-03  
    end_date: null
    mac: !ENV ATMOTUBE_KOL_05_MAC

  - id: atmotube_kol_06
    type: atmotube
    site: kolkata
    timezone: Asia/Kolkata
    start_date: 2026-07-05 
    end_date: null
    mac: !ENV ATMOTUBE_KOL_06_MAC




# STUDY SITES + API cred
# - Fitbit ==> OAuth client (https://console.cloud.google.com/ Cloud Project ID: fitbit-multi-user-dev)
# - Atmotube ==> API key (https://cloud.atmotube.com/ User Account: sensailabs.research@gmail.com)


sites:
  kolkata:
    fitbit_client_secret_path: extract/config/secrets/fitbit/client_secret.json
    atmotube_api_key_site: extract/config/secrets/atmotube/api_key.json
# toronto:
#  fitbit_client_secret_path: extract/config/secrets/fitbit/client_secret.json  # same OAuth client, shared
#  atmotube_api_key_site: ATMOTUBE_API_KEY_TORONTO

